import { Navbar } from "@/components/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main className="w-full min-h-screen">
        <div className="mx-auto max-w-6xl space-y-4 px-4 py-4 lg:px-0">
          {children}
        </div>
      </main>
    </>
  );
}
