import { Navbar } from "@/components/navbar";
import { umamiConfigGet } from "@/lib/dashboard/config/UmamiFormAc";
import type { Metadata } from "next";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const umamiConfig = await umamiConfigGet();
  return (
    <>
      <main className="w-full min-h-screen">
        <Navbar />
        <div className="mx-auto max-w-6xl space-y-4 px-4 py-4 lg:px-0">
          {children}
        </div>
      </main>

      {/* Umami 统计脚本 */}
      {!umamiConfig.success ? (
        <Script
          src={umamiConfig?.data?.config.scripturl || ""}
          data-website-id={umamiConfig?.data?.config.datawebsiteid || ""}
          strategy="lazyOnload"
        />
      ) : (
        ""
      )}
    </>
  );
}
