CREATE INDEX "idx_galrc_account_user_id" ON "galrc_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "idx_galrc_account_provider_id" ON "galrc_account" USING btree ("providerId");--> statement-breakpoint
CREATE INDEX "idx_galrc_account_created_at" ON "galrc_account" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "idx_galrc_session_user_id" ON "galrc_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "idx_galrc_session_created_at" ON "galrc_session" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "idx_galrc_user_role" ON "galrc_user" USING btree ("role");--> statement-breakpoint
CREATE INDEX "idx_galrc_user_created_at" ON "galrc_user" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "idx_galrc_verification_identifier" ON "galrc_verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "idx_galrc_verification_created_at" ON "galrc_verification" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "idx_galrc_alistb_vid" ON "galrc_alistb" USING btree ("vid");--> statement-breakpoint
CREATE INDEX "idx_galrc_alistb_other" ON "galrc_alistb" USING btree ("other");--> statement-breakpoint
CREATE INDEX "idx_galrc_article_vid" ON "galrc_article" USING btree ("vid");--> statement-breakpoint
CREATE INDEX "idx_galrc_article_otherid" ON "galrc_article" USING btree ("otherid");--> statement-breakpoint
CREATE INDEX "idx_galrc_article_author" ON "galrc_article" USING btree ("author");--> statement-breakpoint
CREATE INDEX "idx_galrc_article_type" ON "galrc_article" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_galrc_article_status" ON "galrc_article" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_galrc_article_created_at" ON "galrc_article" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "idx_galrc_comments_target" ON "galrc_comments" USING btree ("targetType","targetId");--> statement-breakpoint
CREATE INDEX "idx_galrc_comments_user_id" ON "galrc_comments" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "idx_galrc_comments_parent_id" ON "galrc_comments" USING btree ("parentId");--> statement-breakpoint
CREATE INDEX "idx_galrc_comments_root_id" ON "galrc_comments" USING btree ("rootId");--> statement-breakpoint
CREATE INDEX "idx_galrc_comments_status" ON "galrc_comments" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_galrc_comments_created_at" ON "galrc_comments" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "idx_galrc_media_type" ON "galrc_media" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_galrc_media_cover" ON "galrc_media" USING btree ("cover");--> statement-breakpoint
CREATE INDEX "idx_galrc_other_media_other_id" ON "galrc_other_media" USING btree ("other_id");--> statement-breakpoint
CREATE INDEX "idx_galrc_other_media_media_hash" ON "galrc_other_media" USING btree ("media_hash");--> statement-breakpoint
CREATE INDEX "idx_galrc_other_media_sort_order" ON "galrc_other_media" USING btree ("sort_order");--> statement-breakpoint
CREATE INDEX "idx_galrc_other_media_created_at" ON "galrc_other_media" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "idx_galrc_other_status" ON "galrc_other" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_galrc_zhtag_exhibition" ON "galrc_zhtag" USING btree ("exhibition");--> statement-breakpoint
CREATE INDEX "idx_producers_type" ON "producers" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_producers_lang" ON "producers" USING btree ("lang");--> statement-breakpoint
CREATE INDEX "idx_producers_relations_id" ON "producers_relations" USING btree ("id");--> statement-breakpoint
CREATE INDEX "idx_producers_relations_pid" ON "producers_relations" USING btree ("pid");--> statement-breakpoint
CREATE INDEX "idx_releases_olang" ON "releases" USING btree ("olang");--> statement-breakpoint
CREATE INDEX "idx_releases_producers_id" ON "releases_producers" USING btree ("id");--> statement-breakpoint
CREATE INDEX "idx_releases_producers_pid" ON "releases_producers" USING btree ("pid");--> statement-breakpoint
CREATE INDEX "idx_releases_titles_id" ON "releases_titles" USING btree ("id");--> statement-breakpoint
CREATE INDEX "idx_releases_titles_lang" ON "releases_titles" USING btree ("lang");--> statement-breakpoint
CREATE INDEX "idx_releases_vn_id" ON "releases_vn" USING btree ("id");--> statement-breakpoint
CREATE INDEX "idx_releases_vn_vid" ON "releases_vn" USING btree ("vid");--> statement-breakpoint
CREATE INDEX "idx_tags_cat" ON "tags" USING btree ("cat");--> statement-breakpoint
CREATE INDEX "idx_tags_vn_tag" ON "tags_vn" USING btree ("tag");--> statement-breakpoint
CREATE INDEX "idx_tags_vn_vid" ON "tags_vn" USING btree ("vid");--> statement-breakpoint
CREATE INDEX "idx_tags_vn_uid" ON "tags_vn" USING btree ("uid");--> statement-breakpoint
CREATE INDEX "idx_vn_olang" ON "vn" USING btree ("olang");--> statement-breakpoint
CREATE INDEX "idx_vn_devstatus" ON "vn" USING btree ("devstatus");--> statement-breakpoint
CREATE INDEX "idx_vn_titles_id" ON "vn_titles" USING btree ("id");--> statement-breakpoint
CREATE INDEX "idx_vn_titles_lang" ON "vn_titles" USING btree ("lang");--> statement-breakpoint
CREATE INDEX "idx_vn_titles_main" ON "vn_titles" USING btree ("main");--> statement-breakpoint
CREATE INDEX "idx_galrc_cloudflare_state" ON "galrc_cloudflare" USING btree ("state");--> statement-breakpoint
CREATE INDEX "idx_galrc_cloudflare_enable" ON "galrc_cloudflare" USING btree ("enable");--> statement-breakpoint
CREATE INDEX "idx_galrc_collections_items_collection_id" ON "galrc_collectionsItems" USING btree ("collection_id");--> statement-breakpoint
CREATE INDEX "idx_galrc_collections_items_game_id" ON "galrc_collectionsItems" USING btree ("game_id");--> statement-breakpoint
CREATE INDEX "idx_galrc_game_download_stats_game_id" ON "galrc_gameDownloadStats" USING btree ("game_id");--> statement-breakpoint
CREATE INDEX "idx_galrc_game_download_stats_created_at" ON "galrc_gameDownloadStats" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_galrc_search_nodes_parent" ON "galrc_search_nodes" USING btree ("parent");--> statement-breakpoint
CREATE INDEX "idx_galrc_search_nodes_name" ON "galrc_search_nodes" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_galrc_setting_items_key" ON "galrc_setting_items" USING btree ("key");--> statement-breakpoint
CREATE INDEX "idx_galrc_setting_items_type" ON "galrc_setting_items" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_galrc_setting_items_group" ON "galrc_setting_items" USING btree ("group");--> statement-breakpoint
CREATE INDEX "idx_galrc_storages_status" ON "galrc_storages" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_galrc_storages_disabled" ON "galrc_storages" USING btree ("disabled");--> statement-breakpoint
CREATE INDEX "idx_galrc_storages_driver" ON "galrc_storages" USING btree ("driver");