import type { Metadata } from "next";
import Providers from "@/components/provider/providers";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { ViewTransitions } from "next-view-transitions";
import { PublicEnvScript } from "next-runtime-env";
import QueryProvider from "@/components/provider/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <head>
          <PublicEnvScript />
        </head>
        <body className={`antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Providers>
              <QueryProvider>{children}</QueryProvider>
            </Providers>
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
