/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenapiRouteImport } from './routes/openapi'
import { Route as FriendLinksRouteImport } from './routes/friend-links'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ProducerIndexRouteImport } from './routes/producer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TagsTagIdRouteImport } from './routes/tags/$tagId'
import { Route as ProducerPidRouteImport } from './routes/producer/$pid'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGameRouteImport } from './routes/api/game'
import { Route as IdLayoutRouteImport } from './routes/$id/_layout'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as IdLayoutIndexRouteImport } from './routes/$id/_layout/index'
import { Route as AuthSignupVerificationRouteImport } from './routes/auth/signup/Verification'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as IdLayoutTranslateRouteImport } from './routes/$id/_layout/translate'
import { Route as IdLayoutCommentRouteImport } from './routes/$id/_layout/comment'
import { Route as IdLayoutIntroductionIndexRouteImport } from './routes/$id/_layout/introduction/index'
import { Route as IdLayoutIntroductionArticleIdRouteImport } from './routes/$id/_layout/introduction/$articleId'

const OpenapiRoute = OpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendLinksRoute = FriendLinksRouteImport.update({
  id: '/friend-links',
  path: '/friend-links',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerIndexRoute = ProducerIndexRouteImport.update({
  id: '/producer/',
  path: '/producer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagIdRoute = TagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerPidRoute = ProducerPidRouteImport.update({
  id: '/producer/$pid',
  path: '/producer/$pid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameRoute = ApiGameRouteImport.update({
  id: '/api/game',
  path: '/api/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IdLayoutRoute = IdLayoutRouteImport.update({
  id: '/$id/_layout',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdLayoutIndexRoute = IdLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdLayoutRoute,
} as any)
const AuthSignupVerificationRoute = AuthSignupVerificationRouteImport.update({
  id: '/auth/signup/Verification',
  path: '/auth/signup/Verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IdLayoutTranslateRoute = IdLayoutTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => IdLayoutRoute,
} as any)
const IdLayoutCommentRoute = IdLayoutCommentRouteImport.update({
  id: '/comment',
  path: '/comment',
  getParentRoute: () => IdLayoutRoute,
} as any)
const IdLayoutIntroductionIndexRoute =
  IdLayoutIntroductionIndexRouteImport.update({
    id: '/introduction/',
    path: '/introduction/',
    getParentRoute: () => IdLayoutRoute,
  } as any)
const IdLayoutIntroductionArticleIdRoute =
  IdLayoutIntroductionArticleIdRouteImport.update({
    id: '/introduction/$articleId',
    path: '/introduction/$articleId',
    getParentRoute: () => IdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/friend-links': typeof FriendLinksRoute
  '/openapi': typeof OpenapiRoute
  '/$id': typeof IdLayoutRouteWithChildren
  '/api/game': typeof ApiGameRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/producer/$pid': typeof ProducerPidRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/admin/': typeof AdminIndexRoute
  '/producer/': typeof ProducerIndexRoute
  '/search/': typeof SearchIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/$id/comment': typeof IdLayoutCommentRoute
  '/$id/translate': typeof IdLayoutTranslateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/signup/Verification': typeof AuthSignupVerificationRoute
  '/$id/': typeof IdLayoutIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/$id/introduction/$articleId': typeof IdLayoutIntroductionArticleIdRoute
  '/$id/introduction/': typeof IdLayoutIntroductionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/friend-links': typeof FriendLinksRoute
  '/openapi': typeof OpenapiRoute
  '/api/game': typeof ApiGameRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/producer/$pid': typeof ProducerPidRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/admin': typeof AdminIndexRoute
  '/producer': typeof ProducerIndexRoute
  '/search': typeof SearchIndexRoute
  '/tags': typeof TagsIndexRoute
  '/$id/comment': typeof IdLayoutCommentRoute
  '/$id/translate': typeof IdLayoutTranslateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/signup/Verification': typeof AuthSignupVerificationRoute
  '/$id': typeof IdLayoutIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/$id/introduction/$articleId': typeof IdLayoutIntroductionArticleIdRoute
  '/$id/introduction': typeof IdLayoutIntroductionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/friend-links': typeof FriendLinksRoute
  '/openapi': typeof OpenapiRoute
  '/$id/_layout': typeof IdLayoutRouteWithChildren
  '/api/game': typeof ApiGameRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/producer/$pid': typeof ProducerPidRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/admin/': typeof AdminIndexRoute
  '/producer/': typeof ProducerIndexRoute
  '/search/': typeof SearchIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/$id/_layout/comment': typeof IdLayoutCommentRoute
  '/$id/_layout/translate': typeof IdLayoutTranslateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/signup/Verification': typeof AuthSignupVerificationRoute
  '/$id/_layout/': typeof IdLayoutIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/$id/_layout/introduction/$articleId': typeof IdLayoutIntroductionArticleIdRoute
  '/$id/_layout/introduction/': typeof IdLayoutIntroductionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/friend-links'
    | '/openapi'
    | '/$id'
    | '/api/game'
    | '/api/health'
    | '/api/search'
    | '/auth/login'
    | '/producer/$pid'
    | '/tags/$tagId'
    | '/admin/'
    | '/producer/'
    | '/search/'
    | '/tags/'
    | '/$id/comment'
    | '/$id/translate'
    | '/api/auth/$'
    | '/auth/signup/Verification'
    | '/$id/'
    | '/auth/signup/'
    | '/$id/introduction/$articleId'
    | '/$id/introduction/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/friend-links'
    | '/openapi'
    | '/api/game'
    | '/api/health'
    | '/api/search'
    | '/auth/login'
    | '/producer/$pid'
    | '/tags/$tagId'
    | '/admin'
    | '/producer'
    | '/search'
    | '/tags'
    | '/$id/comment'
    | '/$id/translate'
    | '/api/auth/$'
    | '/auth/signup/Verification'
    | '/$id'
    | '/auth/signup'
    | '/$id/introduction/$articleId'
    | '/$id/introduction'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/friend-links'
    | '/openapi'
    | '/$id/_layout'
    | '/api/game'
    | '/api/health'
    | '/api/search'
    | '/auth/login'
    | '/producer/$pid'
    | '/tags/$tagId'
    | '/admin/'
    | '/producer/'
    | '/search/'
    | '/tags/'
    | '/$id/_layout/comment'
    | '/$id/_layout/translate'
    | '/api/auth/$'
    | '/auth/signup/Verification'
    | '/$id/_layout/'
    | '/auth/signup/'
    | '/$id/_layout/introduction/$articleId'
    | '/$id/_layout/introduction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FriendLinksRoute: typeof FriendLinksRoute
  OpenapiRoute: typeof OpenapiRoute
  IdLayoutRoute: typeof IdLayoutRouteWithChildren
  ApiGameRoute: typeof ApiGameRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSearchRoute: typeof ApiSearchRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ProducerPidRoute: typeof ProducerPidRoute
  TagsTagIdRoute: typeof TagsTagIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProducerIndexRoute: typeof ProducerIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthSignupVerificationRoute: typeof AuthSignupVerificationRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openapi': {
      id: '/openapi'
      path: '/openapi'
      fullPath: '/openapi'
      preLoaderRoute: typeof OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend-links': {
      id: '/friend-links'
      path: '/friend-links'
      fullPath: '/friend-links'
      preLoaderRoute: typeof FriendLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/': {
      id: '/producer/'
      path: '/producer'
      fullPath: '/producer/'
      preLoaderRoute: typeof ProducerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagId': {
      id: '/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof TagsTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/$pid': {
      id: '/producer/$pid'
      path: '/producer/$pid'
      fullPath: '/producer/$pid'
      preLoaderRoute: typeof ProducerPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game': {
      id: '/api/game'
      path: '/api/game'
      fullPath: '/api/game'
      preLoaderRoute: typeof ApiGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/_layout': {
      id: '/$id/_layout'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/_layout/': {
      id: '/$id/_layout/'
      path: '/'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdLayoutIndexRouteImport
      parentRoute: typeof IdLayoutRoute
    }
    '/auth/signup/Verification': {
      id: '/auth/signup/Verification'
      path: '/auth/signup/Verification'
      fullPath: '/auth/signup/Verification'
      preLoaderRoute: typeof AuthSignupVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/_layout/translate': {
      id: '/$id/_layout/translate'
      path: '/translate'
      fullPath: '/$id/translate'
      preLoaderRoute: typeof IdLayoutTranslateRouteImport
      parentRoute: typeof IdLayoutRoute
    }
    '/$id/_layout/comment': {
      id: '/$id/_layout/comment'
      path: '/comment'
      fullPath: '/$id/comment'
      preLoaderRoute: typeof IdLayoutCommentRouteImport
      parentRoute: typeof IdLayoutRoute
    }
    '/$id/_layout/introduction/': {
      id: '/$id/_layout/introduction/'
      path: '/introduction'
      fullPath: '/$id/introduction/'
      preLoaderRoute: typeof IdLayoutIntroductionIndexRouteImport
      parentRoute: typeof IdLayoutRoute
    }
    '/$id/_layout/introduction/$articleId': {
      id: '/$id/_layout/introduction/$articleId'
      path: '/introduction/$articleId'
      fullPath: '/$id/introduction/$articleId'
      preLoaderRoute: typeof IdLayoutIntroductionArticleIdRouteImport
      parentRoute: typeof IdLayoutRoute
    }
  }
}

interface IdLayoutRouteChildren {
  IdLayoutCommentRoute: typeof IdLayoutCommentRoute
  IdLayoutTranslateRoute: typeof IdLayoutTranslateRoute
  IdLayoutIndexRoute: typeof IdLayoutIndexRoute
  IdLayoutIntroductionArticleIdRoute: typeof IdLayoutIntroductionArticleIdRoute
  IdLayoutIntroductionIndexRoute: typeof IdLayoutIntroductionIndexRoute
}

const IdLayoutRouteChildren: IdLayoutRouteChildren = {
  IdLayoutCommentRoute: IdLayoutCommentRoute,
  IdLayoutTranslateRoute: IdLayoutTranslateRoute,
  IdLayoutIndexRoute: IdLayoutIndexRoute,
  IdLayoutIntroductionArticleIdRoute: IdLayoutIntroductionArticleIdRoute,
  IdLayoutIntroductionIndexRoute: IdLayoutIntroductionIndexRoute,
}

const IdLayoutRouteWithChildren = IdLayoutRoute._addFileChildren(
  IdLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FriendLinksRoute: FriendLinksRoute,
  OpenapiRoute: OpenapiRoute,
  IdLayoutRoute: IdLayoutRouteWithChildren,
  ApiGameRoute: ApiGameRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSearchRoute: ApiSearchRoute,
  AuthLoginRoute: AuthLoginRoute,
  ProducerPidRoute: ProducerPidRoute,
  TagsTagIdRoute: TagsTagIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProducerIndexRoute: ProducerIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthSignupVerificationRoute: AuthSignupVerificationRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
