/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenapiRouteImport } from './routes/openapi'
import { Route as FriendLinksRouteImport } from './routes/friend-links'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ProducerIndexRouteImport } from './routes/producer/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as TopicsCreateRouteImport } from './routes/topics/create'
import { Route as TopicsTopicIdRouteImport } from './routes/topics/$topicId'
import { Route as ToolsPlateRouteImport } from './routes/tools/plate'
import { Route as TagsTagIdRouteImport } from './routes/tags/$tagId'
import { Route as ProducerPidRouteImport } from './routes/producer/$pid'
import { Route as CollectionsIdRouteImport } from './routes/collections/$id'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGameRouteImport } from './routes/api/game'
import { Route as AdminAuthLRouteImport } from './routes/admin/_authL'
import { Route as IdLayoutRouteImport } from './routes/$id/_layout'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as ApiUploadIndexRouteImport } from './routes/api/upload/index'
import { Route as AdminAuthLIndexRouteImport } from './routes/admin/_authL/index'
import { Route as IdLayoutIndexRouteImport } from './routes/$id/_layout/index'
import { Route as TopicsTopicIdEditRouteImport } from './routes/topics/$topicId.edit'
import { Route as AuthSignupVerificationRouteImport } from './routes/auth/signup/Verification'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminAuthLVndbSyncRouteImport } from './routes/admin/_authL/vndb-sync'
import { Route as AdminAuthLUsersRouteImport } from './routes/admin/_authL/users'
import { Route as AdminAuthLTopicsRouteImport } from './routes/admin/_authL/topics'
import { Route as AdminAuthLMeilisearchRouteImport } from './routes/admin/_authL/meilisearch'
import { Route as AdminAuthLCommentsRouteImport } from './routes/admin/_authL/comments'
import { Route as AdminAuthLCollectionsRouteImport } from './routes/admin/_authL/collections'
import { Route as AdminAuthLArticlesRouteImport } from './routes/admin/_authL/articles'
import { Route as IdLayoutTranslateRouteImport } from './routes/$id/_layout/translate'
import { Route as IdLayoutCommentRouteImport } from './routes/$id/_layout/comment'
import { Route as IdLayoutIntroductionIndexRouteImport } from './routes/$id/_layout/introduction/index'
import { Route as IdLayoutIntroductionArticleIdRouteImport } from './routes/$id/_layout/introduction/$articleId'

const OpenapiRoute = OpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendLinksRoute = FriendLinksRouteImport.update({
  id: '/friend-links',
  path: '/friend-links',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerIndexRoute = ProducerIndexRouteImport.update({
  id: '/producer/',
  path: '/producer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsCreateRoute = TopicsCreateRouteImport.update({
  id: '/topics/create',
  path: '/topics/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPlateRoute = ToolsPlateRouteImport.update({
  id: '/tools/plate',
  path: '/tools/plate',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagIdRoute = TagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerPidRoute = ProducerPidRouteImport.update({
  id: '/producer/$pid',
  path: '/producer/$pid',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameRoute = ApiGameRouteImport.update({
  id: '/api/game',
  path: '/api/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthLRoute = AdminAuthLRouteImport.update({
  id: '/admin/_authL',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IdLayoutRoute = IdLayoutRouteImport.update({
  id: '/$id/_layout',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadIndexRoute = ApiUploadIndexRouteImport.update({
  id: '/api/upload/',
  path: '/api/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthLIndexRoute = AdminAuthLIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthLRoute,
} as any)
const IdLayoutIndexRoute = IdLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdLayoutRoute,
} as any)
const TopicsTopicIdEditRoute = TopicsTopicIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TopicsTopicIdRoute,
} as any)
const AuthSignupVerificationRoute = AuthSignupVerificationRouteImport.update({
  id: '/auth/signup/Verification',
  path: '/auth/signup/Verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthLVndbSyncRoute = AdminAuthLVndbSyncRouteImport.update({
  id: '/vndb-sync',
  path: '/vndb-sync',
  getParentRoute: () => AdminAuthLRoute,
} as any)
const AdminAuthLUsersRoute = AdminAuthLUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAuthLRoute,
} as any)
const AdminAuthLTopicsRoute = AdminAuthLTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AdminAuthLRoute,
} as any)
const AdminAuthLMeilisearchRoute = AdminAuthLMeilisearchRouteImport.update({
  id: '/meilisearch',
  path: '/meilisearch',
  getParentRoute: () => AdminAuthLRoute,
} as any)
const AdminAuthLCommentsRoute = AdminAuthLCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminAuthLRoute,
} as any)
const AdminAuthLCollectionsRoute = AdminAuthLCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminAuthLRoute,
} as any)
const AdminAuthLArticlesRoute = AdminAuthLArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminAuthLRoute,
} as any)
const IdLayoutTranslateRoute = IdLayoutTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => IdLayoutRoute,
} as any)
const IdLayoutCommentRoute = IdLayoutCommentRouteImport.update({
  id: '/comment',
  path: '/comment',
  getParentRoute: () => IdLayoutRoute,
} as any)
const IdLayoutIntroductionIndexRoute =
  IdLayoutIntroductionIndexRouteImport.update({
    id: '/introduction/',
    path: '/introduction/',
    getParentRoute: () => IdLayoutRoute,
  } as any)
const IdLayoutIntroductionArticleIdRoute =
  IdLayoutIntroductionArticleIdRouteImport.update({
    id: '/introduction/$articleId',
    path: '/introduction/$articleId',
    getParentRoute: () => IdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/friend-links': typeof FriendLinksRoute
  '/openapi': typeof OpenapiRoute
  '/$id': typeof IdLayoutRouteWithChildren
  '/admin': typeof AdminAuthLRouteWithChildren
  '/api/game': typeof ApiGameRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/producer/$pid': typeof ProducerPidRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tools/plate': typeof ToolsPlateRoute
  '/topics/$topicId': typeof TopicsTopicIdRouteWithChildren
  '/topics/create': typeof TopicsCreateRoute
  '/collections/': typeof CollectionsIndexRoute
  '/producer/': typeof ProducerIndexRoute
  '/search/': typeof SearchIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/user/': typeof UserIndexRoute
  '/$id/comment': typeof IdLayoutCommentRoute
  '/$id/translate': typeof IdLayoutTranslateRoute
  '/admin/articles': typeof AdminAuthLArticlesRoute
  '/admin/collections': typeof AdminAuthLCollectionsRoute
  '/admin/comments': typeof AdminAuthLCommentsRoute
  '/admin/meilisearch': typeof AdminAuthLMeilisearchRoute
  '/admin/topics': typeof AdminAuthLTopicsRoute
  '/admin/users': typeof AdminAuthLUsersRoute
  '/admin/vndb-sync': typeof AdminAuthLVndbSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/signup/Verification': typeof AuthSignupVerificationRoute
  '/topics/$topicId/edit': typeof TopicsTopicIdEditRoute
  '/$id/': typeof IdLayoutIndexRoute
  '/admin/': typeof AdminAuthLIndexRoute
  '/api/upload/': typeof ApiUploadIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/$id/introduction/$articleId': typeof IdLayoutIntroductionArticleIdRoute
  '/$id/introduction/': typeof IdLayoutIntroductionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/friend-links': typeof FriendLinksRoute
  '/openapi': typeof OpenapiRoute
  '/api/game': typeof ApiGameRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/producer/$pid': typeof ProducerPidRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tools/plate': typeof ToolsPlateRoute
  '/topics/$topicId': typeof TopicsTopicIdRouteWithChildren
  '/topics/create': typeof TopicsCreateRoute
  '/collections': typeof CollectionsIndexRoute
  '/producer': typeof ProducerIndexRoute
  '/search': typeof SearchIndexRoute
  '/tags': typeof TagsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/user': typeof UserIndexRoute
  '/$id/comment': typeof IdLayoutCommentRoute
  '/$id/translate': typeof IdLayoutTranslateRoute
  '/admin/articles': typeof AdminAuthLArticlesRoute
  '/admin/collections': typeof AdminAuthLCollectionsRoute
  '/admin/comments': typeof AdminAuthLCommentsRoute
  '/admin/meilisearch': typeof AdminAuthLMeilisearchRoute
  '/admin/topics': typeof AdminAuthLTopicsRoute
  '/admin/users': typeof AdminAuthLUsersRoute
  '/admin/vndb-sync': typeof AdminAuthLVndbSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/signup/Verification': typeof AuthSignupVerificationRoute
  '/topics/$topicId/edit': typeof TopicsTopicIdEditRoute
  '/$id': typeof IdLayoutIndexRoute
  '/admin': typeof AdminAuthLIndexRoute
  '/api/upload': typeof ApiUploadIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/$id/introduction/$articleId': typeof IdLayoutIntroductionArticleIdRoute
  '/$id/introduction': typeof IdLayoutIntroductionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/friend-links': typeof FriendLinksRoute
  '/openapi': typeof OpenapiRoute
  '/$id/_layout': typeof IdLayoutRouteWithChildren
  '/admin/_authL': typeof AdminAuthLRouteWithChildren
  '/api/game': typeof ApiGameRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/producer/$pid': typeof ProducerPidRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/tools/plate': typeof ToolsPlateRoute
  '/topics/$topicId': typeof TopicsTopicIdRouteWithChildren
  '/topics/create': typeof TopicsCreateRoute
  '/collections/': typeof CollectionsIndexRoute
  '/producer/': typeof ProducerIndexRoute
  '/search/': typeof SearchIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/user/': typeof UserIndexRoute
  '/$id/_layout/comment': typeof IdLayoutCommentRoute
  '/$id/_layout/translate': typeof IdLayoutTranslateRoute
  '/admin/_authL/articles': typeof AdminAuthLArticlesRoute
  '/admin/_authL/collections': typeof AdminAuthLCollectionsRoute
  '/admin/_authL/comments': typeof AdminAuthLCommentsRoute
  '/admin/_authL/meilisearch': typeof AdminAuthLMeilisearchRoute
  '/admin/_authL/topics': typeof AdminAuthLTopicsRoute
  '/admin/_authL/users': typeof AdminAuthLUsersRoute
  '/admin/_authL/vndb-sync': typeof AdminAuthLVndbSyncRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/signup/Verification': typeof AuthSignupVerificationRoute
  '/topics/$topicId/edit': typeof TopicsTopicIdEditRoute
  '/$id/_layout/': typeof IdLayoutIndexRoute
  '/admin/_authL/': typeof AdminAuthLIndexRoute
  '/api/upload/': typeof ApiUploadIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/$id/_layout/introduction/$articleId': typeof IdLayoutIntroductionArticleIdRoute
  '/$id/_layout/introduction/': typeof IdLayoutIntroductionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/friend-links'
    | '/openapi'
    | '/$id'
    | '/admin'
    | '/api/game'
    | '/api/health'
    | '/api/search'
    | '/auth/login'
    | '/collections/$id'
    | '/producer/$pid'
    | '/tags/$tagId'
    | '/tools/plate'
    | '/topics/$topicId'
    | '/topics/create'
    | '/collections/'
    | '/producer/'
    | '/search/'
    | '/tags/'
    | '/tools/'
    | '/topics/'
    | '/user/'
    | '/$id/comment'
    | '/$id/translate'
    | '/admin/articles'
    | '/admin/collections'
    | '/admin/comments'
    | '/admin/meilisearch'
    | '/admin/topics'
    | '/admin/users'
    | '/admin/vndb-sync'
    | '/api/auth/$'
    | '/auth/signup/Verification'
    | '/topics/$topicId/edit'
    | '/$id/'
    | '/admin/'
    | '/api/upload/'
    | '/auth/signup/'
    | '/$id/introduction/$articleId'
    | '/$id/introduction/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/friend-links'
    | '/openapi'
    | '/api/game'
    | '/api/health'
    | '/api/search'
    | '/auth/login'
    | '/collections/$id'
    | '/producer/$pid'
    | '/tags/$tagId'
    | '/tools/plate'
    | '/topics/$topicId'
    | '/topics/create'
    | '/collections'
    | '/producer'
    | '/search'
    | '/tags'
    | '/tools'
    | '/topics'
    | '/user'
    | '/$id/comment'
    | '/$id/translate'
    | '/admin/articles'
    | '/admin/collections'
    | '/admin/comments'
    | '/admin/meilisearch'
    | '/admin/topics'
    | '/admin/users'
    | '/admin/vndb-sync'
    | '/api/auth/$'
    | '/auth/signup/Verification'
    | '/topics/$topicId/edit'
    | '/$id'
    | '/admin'
    | '/api/upload'
    | '/auth/signup'
    | '/$id/introduction/$articleId'
    | '/$id/introduction'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/friend-links'
    | '/openapi'
    | '/$id/_layout'
    | '/admin/_authL'
    | '/api/game'
    | '/api/health'
    | '/api/search'
    | '/auth/login'
    | '/collections/$id'
    | '/producer/$pid'
    | '/tags/$tagId'
    | '/tools/plate'
    | '/topics/$topicId'
    | '/topics/create'
    | '/collections/'
    | '/producer/'
    | '/search/'
    | '/tags/'
    | '/tools/'
    | '/topics/'
    | '/user/'
    | '/$id/_layout/comment'
    | '/$id/_layout/translate'
    | '/admin/_authL/articles'
    | '/admin/_authL/collections'
    | '/admin/_authL/comments'
    | '/admin/_authL/meilisearch'
    | '/admin/_authL/topics'
    | '/admin/_authL/users'
    | '/admin/_authL/vndb-sync'
    | '/api/auth/$'
    | '/auth/signup/Verification'
    | '/topics/$topicId/edit'
    | '/$id/_layout/'
    | '/admin/_authL/'
    | '/api/upload/'
    | '/auth/signup/'
    | '/$id/_layout/introduction/$articleId'
    | '/$id/_layout/introduction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FriendLinksRoute: typeof FriendLinksRoute
  OpenapiRoute: typeof OpenapiRoute
  IdLayoutRoute: typeof IdLayoutRouteWithChildren
  AdminAuthLRoute: typeof AdminAuthLRouteWithChildren
  ApiGameRoute: typeof ApiGameRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSearchRoute: typeof ApiSearchRoute
  AuthLoginRoute: typeof AuthLoginRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  ProducerPidRoute: typeof ProducerPidRoute
  TagsTagIdRoute: typeof TagsTagIdRoute
  ToolsPlateRoute: typeof ToolsPlateRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRouteWithChildren
  TopicsCreateRoute: typeof TopicsCreateRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ProducerIndexRoute: typeof ProducerIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthSignupVerificationRoute: typeof AuthSignupVerificationRoute
  ApiUploadIndexRoute: typeof ApiUploadIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openapi': {
      id: '/openapi'
      path: '/openapi'
      fullPath: '/openapi'
      preLoaderRoute: typeof OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend-links': {
      id: '/friend-links'
      path: '/friend-links'
      fullPath: '/friend-links'
      preLoaderRoute: typeof FriendLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/': {
      id: '/producer/'
      path: '/producer'
      fullPath: '/producer/'
      preLoaderRoute: typeof ProducerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/create': {
      id: '/topics/create'
      path: '/topics/create'
      fullPath: '/topics/create'
      preLoaderRoute: typeof TopicsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/plate': {
      id: '/tools/plate'
      path: '/tools/plate'
      fullPath: '/tools/plate'
      preLoaderRoute: typeof ToolsPlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagId': {
      id: '/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof TagsTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/$pid': {
      id: '/producer/$pid'
      path: '/producer/$pid'
      fullPath: '/producer/$pid'
      preLoaderRoute: typeof ProducerPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game': {
      id: '/api/game'
      path: '/api/game'
      fullPath: '/api/game'
      preLoaderRoute: typeof ApiGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authL': {
      id: '/admin/_authL'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthLRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/_layout': {
      id: '/$id/_layout'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/': {
      id: '/api/upload/'
      path: '/api/upload'
      fullPath: '/api/upload/'
      preLoaderRoute: typeof ApiUploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authL/': {
      id: '/admin/_authL/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthLIndexRouteImport
      parentRoute: typeof AdminAuthLRoute
    }
    '/$id/_layout/': {
      id: '/$id/_layout/'
      path: '/'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdLayoutIndexRouteImport
      parentRoute: typeof IdLayoutRoute
    }
    '/topics/$topicId/edit': {
      id: '/topics/$topicId/edit'
      path: '/edit'
      fullPath: '/topics/$topicId/edit'
      preLoaderRoute: typeof TopicsTopicIdEditRouteImport
      parentRoute: typeof TopicsTopicIdRoute
    }
    '/auth/signup/Verification': {
      id: '/auth/signup/Verification'
      path: '/auth/signup/Verification'
      fullPath: '/auth/signup/Verification'
      preLoaderRoute: typeof AuthSignupVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authL/vndb-sync': {
      id: '/admin/_authL/vndb-sync'
      path: '/vndb-sync'
      fullPath: '/admin/vndb-sync'
      preLoaderRoute: typeof AdminAuthLVndbSyncRouteImport
      parentRoute: typeof AdminAuthLRoute
    }
    '/admin/_authL/users': {
      id: '/admin/_authL/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthLUsersRouteImport
      parentRoute: typeof AdminAuthLRoute
    }
    '/admin/_authL/topics': {
      id: '/admin/_authL/topics'
      path: '/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AdminAuthLTopicsRouteImport
      parentRoute: typeof AdminAuthLRoute
    }
    '/admin/_authL/meilisearch': {
      id: '/admin/_authL/meilisearch'
      path: '/meilisearch'
      fullPath: '/admin/meilisearch'
      preLoaderRoute: typeof AdminAuthLMeilisearchRouteImport
      parentRoute: typeof AdminAuthLRoute
    }
    '/admin/_authL/comments': {
      id: '/admin/_authL/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminAuthLCommentsRouteImport
      parentRoute: typeof AdminAuthLRoute
    }
    '/admin/_authL/collections': {
      id: '/admin/_authL/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminAuthLCollectionsRouteImport
      parentRoute: typeof AdminAuthLRoute
    }
    '/admin/_authL/articles': {
      id: '/admin/_authL/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminAuthLArticlesRouteImport
      parentRoute: typeof AdminAuthLRoute
    }
    '/$id/_layout/translate': {
      id: '/$id/_layout/translate'
      path: '/translate'
      fullPath: '/$id/translate'
      preLoaderRoute: typeof IdLayoutTranslateRouteImport
      parentRoute: typeof IdLayoutRoute
    }
    '/$id/_layout/comment': {
      id: '/$id/_layout/comment'
      path: '/comment'
      fullPath: '/$id/comment'
      preLoaderRoute: typeof IdLayoutCommentRouteImport
      parentRoute: typeof IdLayoutRoute
    }
    '/$id/_layout/introduction/': {
      id: '/$id/_layout/introduction/'
      path: '/introduction'
      fullPath: '/$id/introduction/'
      preLoaderRoute: typeof IdLayoutIntroductionIndexRouteImport
      parentRoute: typeof IdLayoutRoute
    }
    '/$id/_layout/introduction/$articleId': {
      id: '/$id/_layout/introduction/$articleId'
      path: '/introduction/$articleId'
      fullPath: '/$id/introduction/$articleId'
      preLoaderRoute: typeof IdLayoutIntroductionArticleIdRouteImport
      parentRoute: typeof IdLayoutRoute
    }
  }
}

interface IdLayoutRouteChildren {
  IdLayoutCommentRoute: typeof IdLayoutCommentRoute
  IdLayoutTranslateRoute: typeof IdLayoutTranslateRoute
  IdLayoutIndexRoute: typeof IdLayoutIndexRoute
  IdLayoutIntroductionArticleIdRoute: typeof IdLayoutIntroductionArticleIdRoute
  IdLayoutIntroductionIndexRoute: typeof IdLayoutIntroductionIndexRoute
}

const IdLayoutRouteChildren: IdLayoutRouteChildren = {
  IdLayoutCommentRoute: IdLayoutCommentRoute,
  IdLayoutTranslateRoute: IdLayoutTranslateRoute,
  IdLayoutIndexRoute: IdLayoutIndexRoute,
  IdLayoutIntroductionArticleIdRoute: IdLayoutIntroductionArticleIdRoute,
  IdLayoutIntroductionIndexRoute: IdLayoutIntroductionIndexRoute,
}

const IdLayoutRouteWithChildren = IdLayoutRoute._addFileChildren(
  IdLayoutRouteChildren,
)

interface AdminAuthLRouteChildren {
  AdminAuthLArticlesRoute: typeof AdminAuthLArticlesRoute
  AdminAuthLCollectionsRoute: typeof AdminAuthLCollectionsRoute
  AdminAuthLCommentsRoute: typeof AdminAuthLCommentsRoute
  AdminAuthLMeilisearchRoute: typeof AdminAuthLMeilisearchRoute
  AdminAuthLTopicsRoute: typeof AdminAuthLTopicsRoute
  AdminAuthLUsersRoute: typeof AdminAuthLUsersRoute
  AdminAuthLVndbSyncRoute: typeof AdminAuthLVndbSyncRoute
  AdminAuthLIndexRoute: typeof AdminAuthLIndexRoute
}

const AdminAuthLRouteChildren: AdminAuthLRouteChildren = {
  AdminAuthLArticlesRoute: AdminAuthLArticlesRoute,
  AdminAuthLCollectionsRoute: AdminAuthLCollectionsRoute,
  AdminAuthLCommentsRoute: AdminAuthLCommentsRoute,
  AdminAuthLMeilisearchRoute: AdminAuthLMeilisearchRoute,
  AdminAuthLTopicsRoute: AdminAuthLTopicsRoute,
  AdminAuthLUsersRoute: AdminAuthLUsersRoute,
  AdminAuthLVndbSyncRoute: AdminAuthLVndbSyncRoute,
  AdminAuthLIndexRoute: AdminAuthLIndexRoute,
}

const AdminAuthLRouteWithChildren = AdminAuthLRoute._addFileChildren(
  AdminAuthLRouteChildren,
)

interface TopicsTopicIdRouteChildren {
  TopicsTopicIdEditRoute: typeof TopicsTopicIdEditRoute
}

const TopicsTopicIdRouteChildren: TopicsTopicIdRouteChildren = {
  TopicsTopicIdEditRoute: TopicsTopicIdEditRoute,
}

const TopicsTopicIdRouteWithChildren = TopicsTopicIdRoute._addFileChildren(
  TopicsTopicIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FriendLinksRoute: FriendLinksRoute,
  OpenapiRoute: OpenapiRoute,
  IdLayoutRoute: IdLayoutRouteWithChildren,
  AdminAuthLRoute: AdminAuthLRouteWithChildren,
  ApiGameRoute: ApiGameRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSearchRoute: ApiSearchRoute,
  AuthLoginRoute: AuthLoginRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  ProducerPidRoute: ProducerPidRoute,
  TagsTagIdRoute: TagsTagIdRoute,
  ToolsPlateRoute: ToolsPlateRoute,
  TopicsTopicIdRoute: TopicsTopicIdRouteWithChildren,
  TopicsCreateRoute: TopicsCreateRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ProducerIndexRoute: ProducerIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  UserIndexRoute: UserIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthSignupVerificationRoute: AuthSignupVerificationRoute,
  ApiUploadIndexRoute: ApiUploadIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
