import type { Metadata } from "next";

import {
  SidebarProvider,
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarRail,
} from "@/components/animate-ui/radix/sidebar";
import Switcher from "@/components/dashboard/sedebar/Switcher";
import NavMain from "@/components/dashboard/sedebar/NavMain";
import NavProject from "@/components/dashboard/sedebar/NavProject";
import NavUser from "@/components/dashboard/sedebar/NavUser";
import SideContent from "@/components/dashboard/sedebar/sideContent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SidebarProvider>
        <Sidebar collapsible="icon">
          <SidebarContent>
            <Switcher />
            <NavMain />
            <NavProject />
          </SidebarContent>
          <SidebarFooter>
            <NavUser />
          </SidebarFooter>
          <SidebarRail />
        </Sidebar>
        <SideContent>{children}</SideContent>
      </SidebarProvider>
    </>
  );
}
