name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 安装 Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # 构建 Docker 镜像
      - name: Build Docker images with Bun
        run: bun docker

      # 登录 GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 获取本地镜像版本号并推送
      - name: Tag and Push Docker images
        run: |
          # 获取镜像版本号
          VERSION_API=$(docker images mono-api --format "{{.Tag}}")
          VERSION_WEB=$(docker images mono-web --format "{{.Tag}}")

          echo "API version: $VERSION_API"
          echo "WEB version: $VERSION_WEB"

          # 自动判断仓库命名空间
          if [ "${{ github.repository_owner }}" = "${{ github.actor }}" ]; then
            # 个人仓库
            GHCR_NAMESPACE=${{ github.actor }}
          else
            # 组织仓库
            GHCR_NAMESPACE=${{ github.repository_owner }}
          fi

          echo "Using GHCR namespace: $GHCR_NAMESPACE"

          # 打标签
          docker tag mono-api:$VERSION_API ghcr.io/$GHCR_NAMESPACE/mono-api:$VERSION_API
          docker tag mono-api:$VERSION_API ghcr.io/$GHCR_NAMESPACE/mono-api:latest

          docker tag mono-web:$VERSION_WEB ghcr.io/$GHCR_NAMESPACE/mono-web:$VERSION_WEB
          docker tag mono-web:$VERSION_WEB ghcr.io/$GHCR_NAMESPACE/mono-web:latest

          # 推送镜像
          docker push ghcr.io/$GHCR_NAMESPACE/mono-api:$VERSION_API
          docker push ghcr.io/$GHCR_NAMESPACE/mono-api:latest

          docker push ghcr.io/$GHCR_NAMESPACE/mono-web:$VERSION_WEB
          docker push ghcr.io/$GHCR_NAMESPACE/mono-web:latest
        shell: bash
