name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 监听 main 分支提交

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js 和 Bun
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 根据你项目实际需要

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      # 安装依赖
      - name: Install dependencies
        run: bun install

      # 构建 Docker 镜像
      - name: Build Docker image (API)
        run: bun docker

      # 登录 GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 推送 Docker 镜像 (API)
      - name: Push Docker image (API)
        run: |
          VERSION=$(node -e "console.log(require('./apps/api/package.json').version)")
          docker tag mono-api:$VERSION ghcr.io/${{ github.repository }}/mono-api:$VERSION
          docker push ghcr.io/${{ github.repository }}/mono-api:$VERSION

      # 推送 Docker 镜像 (Web)
      - name: Push Docker image (Web)
        run: |
          VERSION=$(node -e "console.log(require('./apps/web/package.json').version)")
          docker tag mono-web:$VERSION ghcr.io/${{ github.repository }}/mono-web:$VERSION
          docker push ghcr.io/${{ github.repository }}/mono-web:$VERSION
