name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 监听 main 分支提交

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 按需调整

      # 登录 GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 构建并推送 API 镜像
      - name: Build and Push API Docker image
        run: |
          VERSION=$(node -e "console.log(require('./apps/api/package.json').version)")
          IMAGE=ghcr.io/${{ github.repository }}/mono-api:$VERSION
          docker build -t $IMAGE ./apps/api
          docker push $IMAGE

      # 构建并推送 Web 镜像
      - name: Build and Push Web Docker image
        run: |
          VERSION=$(node -e "console.log(require('./apps/web/package.json').version)")
          IMAGE=ghcr.io/${{ github.repository }}/mono-web:$VERSION
          docker build -t $IMAGE ./apps/web
          docker push $IMAGE
